name: builder

on:
  push:
    branches: [ actions ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: build
      run: |
        sudo apt update
        sudo apt install build-essential autoconf automake libtool nasm yasm openjdk-8-jdk mingw-w64
        wget https://github.com/intel/isa-l/archive/master.zip
        unzip master.zip
        cp Makefile.am isa-l-master/
        cp -a igzip-java/src/main/c isa-l-master/
        mkdir out
        # build linux
        cp -a isa-l-master build
        cd build
        ./autogen.sh
        CFLAGS="-O3 -fPIC" ./configure
        make -j`nproc`
        gcc -shared -s -O3 -I include/ -I /usr/lib/jvm/java-1.8.0-openjdk-amd64/include/ -I /usr/lib/jvm/java-1.8.0-openjdk-amd64/include/linux/ c/igzip_jni.c .libs/libisal.a -o ../out/libigzip_jni.so
        # build windows
        cd ../
        rm -rf build
        cp -a isa-l-master build
        cd build
        ./autogen.sh
        CFLAGS="-O3 -fPIC" ./configure --host=x86_64-w64-mingw32
        make -j`nproc`
        x86_64-w64-mingw32-gcc -shared -s -O3 -I include/ -I /usr/lib/jvm/java-1.8.0-openjdk-amd64/include/ -I /usr/lib/jvm/java-1.8.0-openjdk-amd64/include/linux/ c/igzip_jni.c .libs/libisal.a -o ../out/igzip_jni.dll

    - uses: actions/upload-artifact@v2
      with:
        path: out/

